### PR TITLE
Create a Markdownlint configuration file

### PR DESCRIPTION
**Pull request by desrosj**
Markdownlint can be passed a configuration file to control which rules are checked when checking markdown files.

Code Climate supports the use of this file, so let's create one that can be shared the same way our SASS and JS linting configuration files are.

### CODE REVIEW

**Comment by desrosj** [comment]
There is exceptional documentation for each rule located here: [https://updownpress.github.io/markdown-lint](https://updownpress.github.io/markdown-lint).

Going to use this, paired with [the README.md in the Markdownlint project](https://github.com/DavidAnson/markdownlint/blob/master/README.md) to expand this configuration file.

**Comment by desrosj** [comment]
I added a few more rules, and also adjusted a few. Here are my adjustments with rationale.
**Use 'one' style for ordered lists**
Using `1.` at the beginning of each list item makes it much easier to reorder items. If you want to change a list item in the middle of the list, you don’t have to modify all items that follow it. Diffs will show only the significant line which was modified because the preceding number will not change.

**Line Length**
I would like to leave this restriction in place. First reason is similar to above, where commit diffs are cleaner and easier to read. Longer lines also do not read well. Code editors usually have character counters in their bottom toolbars, and limits on line length can usually be configured in code editors.

**Comment by desrosj** [comment]
Also, I am unable to get the horizontal line rule to properly check for the specified style parameter. @ashleykolodziej I can help you set up Code Climate to run locally so that you can see if you have better luck with it than me.

**Comment by ashleykolodziej** [comment]
This is fantastic! The new formatting is way clearer. 👍 

With regards to line length, these are the types of things that are getting caught by that filter - I don't see a more brief way to write these without making our changelog unclear. So we definitely need to up the line length if we're going to keep it.

screen shot 2017-02-24 at 10 34 10 am

**Comment by desrosj** [comment]
Updated the line length rule. I submitted a support ticket because I can't get the engine to respect our configuration file locally. Hoping the Code Climate team can shed some light on why. Leaving this open until I hear back.

**Comment by desrosj** [comment]
Following up on this with a status update. Still going back and forth with Code Climate trying to figure out exactly what is happening with this and why our linting rules are not bing respected.

**Comment by desrosj** [comment]
This is working now! Going to merge and close this.

**Pull request merged**
