### PR TITLE
PHPbin Coding Standards

### PR DESCRIPTION
**Pull request by Adam42**
Creates a baseline PHPbin coding standards document and includes a base `phpcs.xml` file that can be used as a starting point for sniffing PHPbin applications. Both the standards and phpcs file should be considered WIP for a while as we're just now beginning to apply both to our PHPbin codebase. During this initial phase we may discover more WP specific sniffs to exclude or may want to bring in other rule-sets and sniffs such as those proposed here: https://github.com/bu-ist/phpbin-homepage/pull/95

But for now, this PR should be a minimally controversial ( or better yet non-controversial! ) starting point for us to build on.

### CODE REVIEW

**Comment by Adam42** [comment]
TODO?: 
1. Rename `phpcs.xml` to `phpcs-phpbin.xml`.
1. Add instructions to include `phpcs-phpbin.xml` as a dep, (git submodule?).
1. Add instructions to `cp pphpcs-phpbin.xml phpcs.xml` in app repo.

**Comment by Adam42** [comment]
Propose leaving the standards for naming variables and methods to each application. https://github.com/bu-ist/phpbin-bu-alert-emergency/blob/master/index.php#L84 can remove the exclusion of snake_case variables as its' convention is snake_case_variables. 

And apps like homepage can instead add rules for camelCase like so: https://github.com/bu-ist/phpbin-homepage/commit/0b4ee929dc1b190b1c299bf8ee3d00ada0864bda

**Comment by Adam42** [comment]
Unless anyone objects I plan to merge this (into `develop`) tomorrow as version 0.1 of our phpbin coding standards!

**Comment by Adam42** [comment]
Problem with adding a standard to do camelCase is many apps (BU Alert off the top of my head) use snake_case. And many others use camelCase.

At one point was going to add a camelCase phpcs and a snake_case phpcs so each app could use whichever is more appropriate but that doesn't seem like an ideal solution to have two standards but I'm not sure how to solve it.

Maybe this can be the base and there's supplemental files for naming convention?

**Comment by Adam42** [comment]
I've added standards to use camelCase for variables and methods in the default phpcs.xml file. I've also added a snake case variant for other apps. If there are no other objections I'll be merging this in tomorrow.

**Comment by Adam42** [comment]
Food for thought: http://www.richardrodger.com/2012/11/03/why-i-have-given-up-on-coding-standards/#.W34NwVApB-E

The article makes a lot of points, I like freedom, and maybe the best thing is to let each app/developer dictate the standard for a codebase, or even decide to not have any standards.

My main desire is to be able to auto-format, we don't need one standard to rule them all for that.

**Comment by bfenster** [comment]
Those are fair points, but it should drive a policy of "Turn off auto-formatting or use different standards or use no standards at all when that makes sense for the project."

But we still need a single standard underlying that. The reason I was so pushy about consistency with WordPress is precisely that there's benefit to be had in lots of code from lots of people on lots of projects all being structured the same way.

We should just formally acknowledge that there will absolutely be times I turn off the auto-formatting and do whatever I want in a particular project (e.g., We Remember) or switch to some deviant ruleset that better matches how a particular project is already built (e.g., MediaWiki).

But when it's time to start writing the new Dining plugin, or the new Nelnet integration, or the new _____, that's not a time to do whatever I want however I want; that's a time to use the standard formatting everybody else is using.

**Comment by Adam42** [comment]
So with the two phpcs.xml files now in here, we have a standard(s) that will cover a majority of our phpbin apps, I think? So for existing apps, one of these two should be ok, at least as a base.

The real question is if we have a new PHP app which one do we use? The snake case variant that is closer to WP but further from mainstream modern PHP (where I think everyone has moved to camelCase) or the camelCase that goes against WP but would match other modern PHP?

**Comment by Adam42** [comment]
Unless anyone objects I'd vote for using the camelCase way as the default for new PHPbin apps and just live with that variance between PHPbin and WP as it'll match frameworks and libraries but I'm perfectly fine with going with snake_case for new PHP if that gets us to a formal published standard.

Or we just figure that out when we actually have a new PHP app?

**Comment by Adam42** [comment]
I'm going to add a link in the main README to the phpbin standards and then merge this in. These standards are not perfect but are our first draft and the goal of this PR was to simply codify some standard instead of the current state of anarchy with no standard at all.

If you object please speak up ASAP.

**Pull request merged**
